include!("src/app_commands.rs");

fn main() {
    // tauri-build reads STATIC_VCRUNTIME on Windows but does not ask Cargo to
    // rerun when it changes, so a plain `cargo build` could keep stale CRT
    // link arguments from a previous `cargo tauri build`.
    println!("cargo:rerun-if-env-changed=STATIC_VCRUNTIME");
    // tauri-build prints its own rerun-if-changed lines, which turns off
    // Cargo's default "rerun when any file changes", so name this one too.
    println!("cargo:rerun-if-changed=src/app_commands.rs");

    // An app ACL manifest: Tauri then checks every app command against the
    // window's capabilities (capabilities/*.json), so the island window can
    // call only the two commands it uses. Without a manifest, every command
    // is callable from every local window. The generated permission files go
    // to permissions/autogenerated/ (not committed).
    let attributes = tauri_build::Attributes::new()
        .app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS));
    if let Err(error) = tauri_build::try_build(attributes) {
        panic!("tauri-build failed: {error:#}");
    }
}
